version: '3.5'
services:
  kibana:
    # image: docker.elastic.co/kibana/kibana:7.5.1
    # image: wazuh/wazuh-kibana:3.10.2_7.3.2
    image: docker.elastic.co/kibana/kibana:7.3.2
    container_name: kibana
    # environment:
    #   ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    volumes:
      - ${PWD}/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  default:
    external:
      name: my

