apiVersion: v1
kind: Pod
metadata:
  name: varnish
spec:
  containers:
    - name: varnish
      image: varnish:6.0.6
      # resources:
      #   requests:
      #     cpu: 100m
      #     memory: 128Mi
      command: ["tail", "-f", "/dev/null"]
