# `kubectl api-resources` show all types

kubectl -n "$1" --ignore-not-found get bindings
kubectl -n "$1" --ignore-not-found get configmaps
kubectl -n "$1" --ignore-not-found get endpoints
kubectl -n "$1" --ignore-not-found get events
kubectl -n "$1" --ignore-not-found get limitranges
kubectl -n "$1" --ignore-not-found get persistentvolumeclaims
kubectl -n "$1" --ignore-not-found get pods
kubectl -n "$1" --ignore-not-found get podtemplates
kubectl -n "$1" --ignore-not-found get replicationcontrollers
kubectl -n "$1" --ignore-not-found get resourcequotas
kubectl -n "$1" --ignore-not-found get secrets
kubectl -n "$1" --ignore-not-found get serviceaccounts
kubectl -n "$1" --ignore-not-found get services
kubectl -n "$1" --ignore-not-found get controllerrevisions
kubectl -n "$1" --ignore-not-found get daemonsets
kubectl -n "$1" --ignore-not-found get deployments
kubectl -n "$1" --ignore-not-found get replicasets
kubectl -n "$1" --ignore-not-found get statefulsets
kubectl -n "$1" --ignore-not-found get localsubjectaccessreviews
kubectl -n "$1" --ignore-not-found get horizontalpodautoscalers
kubectl -n "$1" --ignore-not-found get cronjobs
kubectl -n "$1" --ignore-not-found get jobs
kubectl -n "$1" --ignore-not-found get leases
kubectl -n "$1" --ignore-not-found get events
kubectl -n "$1" --ignore-not-found get daemonsets
kubectl -n "$1" --ignore-not-found get deployments
kubectl -n "$1" --ignore-not-found get ingresses
kubectl -n "$1" --ignore-not-found get networkpolicies
kubectl -n "$1" --ignore-not-found get replicasets
kubectl -n "$1" --ignore-not-found get ingresses
kubectl -n "$1" --ignore-not-found get networkpolicies
kubectl -n "$1" --ignore-not-found get poddisruptionbudgets
kubectl -n "$1" --ignore-not-found get rolebindings
kubectl -n "$1" --ignore-not-found get roles
