version: "3.5"
services:
  filebeat:
    user: root
    # user: ${CURRENT_UID}
    image: docker.elastic.co/beats/filebeat:7.4.0
    container_name: filebeat
    ulimits:
      nofile:
        soft: 30000
        hard: 30000
    volumes:
      - "./data/:/usr/share/filebeat/data/"
      - "./logs/:/usr/share/filebeat/logs"
      - "./tmp/:/tmp"
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - filebeat
      - -e
      - -strict.perms=false

networks:
  default:
    external:
      name: my

