version: "3.5"
services:
  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:7.4.0
    container_name: filebeat
    network_mode: host
    ulimits:
      nofile:
        soft: 60000
        hard: 60000
    volumes:
      - "${PWD}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - filebeat
      - -e
      - -strict.perms=false
